export PS1="\[\033[01;32m\][\u@\h\[\033[01;37m\] \W\[\033[01;32m\]]\$\[\033[00m\] "
export PATH=/home/Projet GL/global/bin:$PATH



PATH=$M2_HOME/bin:"$PATH"
PATH=/matieres/4MMPGL/GL/global/bin:"$PATH"
PATH=$JAVA_HOME/bin:"$PATH"
PATH=$HOME/Projet GL/src/main/bin:"$PATH"
PATH=$HOME/Projet GL/src/test/script:"$PATH"
PATH=$HOME/Projet GL/src/test/script/launchers:"$PATH"

export M2_HOME=/opt/maven
export MAVEN_HOME=/opt/maven
export PATH=${M2_HOME}/bin:${PATH}

export PATH